### PR TITLE
add github actions to run tests

### PR DESCRIPTION
**Pull request by TripleDogDare**
This is ready!

https://github.com/TripleDogDare/go-serum-analyzer/actions/runs/3826243667/jobs/6509883570

### CODE REVIEW

**Comment by TripleDogDare** [comment]
It looks like _most_ of the errors are around the `Cause` function which doesn't have an obvious solution for real use, although some of these contrived cases would probably be fine using `// Errors: none`.
```
    analysistest.go:446: 001/main.go:153:1: unexpected diagnostic: function "DereferenceAssignment" has a mismatch of declared and actual error codes: unused codes: [other-error]
    analysistest.go:446: 001/main.go:164:1: unexpected diagnostic: function "DereferenceAssignment2" has a mismatch of declared and actual error codes: unused codes: [other-error]
    analysistest.go:446: 001/main.go:220:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: annotation/annotation.go:153:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: docformat/docformat.go:320:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: dotimport/dotimport.go:113:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: dotimport/inner1/inner1.go:29:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: error_constructor/error_constructor.go:200:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: field_assignment/field_assignment.go:135:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: field_assignment/field_assignment.go:145:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: func_literal/func_literal.go:239:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: interfaces/inner1/inner1.go:156:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: interfaces/interfaces.go:180:2: unexpected diagnostic: interface method "Cause" does not declare any error codes
    analysistest.go:446: interfaces/interfaces.go:210:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: methods/methods.go:279:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: multifile/file1.go:17:1: unexpected diagnostic: function "DoString" has a mismatch of declared and actual error codes: unused codes: [string-error]
    analysistest.go:446: multifile/file1.go:18:9: unexpected diagnostic: function "StringError" in dot-imported package does not declare error codes
    analysistest.go:446: multifile/file1.go:38:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: multipackage/inner1/inner1.go:29:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: multipackage/multipackage.go:138:1: unexpected diagnostic: function "DoString" has a mismatch of declared and actual error codes: unused codes: [string-error]
    analysistest.go:446: multipackage/multipackage.go:139:9: unexpected diagnostic: function "StringError" in package "inner1" does not declare error codes
    analysistest.go:446: multipackage/multipackage.go:149:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
    analysistest.go:446: recursion/recursion.go:231:1: unexpected diagnostic: function "Cause" is exported, but does not declare any error codes
```

**Comment by TripleDogDare** [comment]
So the `Cause()` functions we can ignore and add expected diagnostics. The rest of them I added `FIXME` around because they seem more like incomplete features.

**Comment by TripleDogDare** [comment]
what the actual heck.

```
 ~/repos/warpforge/go-serum-analyzer (add-ci) $ go1.18 test ./...
ok  	github.com/serum-errors/go-serum-analyzer/analysis	(cached)
ok  	github.com/serum-errors/go-serum-analyzer/analysis/scc	(cached)
?   	github.com/serum-errors/go-serum-analyzer/cmd/go-serum-analyzer	[no test files]
 ~/repos/warpforge/go-serum-analyzer (add-ci) $ go1.17 test ./...
--- FAIL: TestVerifyAnalyzer (1.34s)
    analysistest.go:512: 001/main.go:224: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: annotation/annotation.go:153: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: docformat/docformat.go:320: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: dotimport/inner1/inner1.go:29: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: dotimport/dotimport.go:113: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: error_constructor/error_constructor.go:200: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: field_assignment/field_assignment.go:135: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: field_assignment/field_assignment.go:145: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: func_literal/func_literal.go:239: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: interfaces/inner1/inner1.go:156: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: interfaces/interfaces.go:180: no diagnostic was reported matching "interface method \"Cause\" does not declare any error codes"
    analysistest.go:512: interfaces/interfaces.go:210: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: methods/methods.go:279: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: multifile/file1.go:40: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: multipackage/inner1/inner1.go:29: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: multipackage/multipackage.go:151: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
    analysistest.go:512: recursion/recursion.go:231: no diagnostic was reported matching "function \"Cause\" is exported, but does not declare any error codes"
FAIL
FAIL	github.com/serum-errors/go-serum-analyzer/analysis	1.358s
ok  	github.com/serum-errors/go-serum-analyzer/analysis/scc	(cached)
?   	github.com/serum-errors/go-serum-analyzer/cmd/go-serum-analyzer	[no test files]
FAIL
```

**Comment by TripleDogDare** [comment]
#5 should fix all the errors above. I added some changes to handle the currently failing tests (not implemented features) and we should be good to go.

**Comment by TripleDogDare** [comment]
@warpfork review request

**Review by warpfork — APPROVED** [review]

**Pull request merged**
